//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invertory._1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [Key]
        public int u_id { get; set; }

        [Display(Name ="Name")]
        [Required(ErrorMessage ="*")]
        public string u_name { get; set; }

        [Display(Name = "User Name")]
        [Required(ErrorMessage = "*")]
        public string u_username { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        [Required(ErrorMessage = "*")]
        public string u_password { get; set; }

        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        [Required(ErrorMessage = "*")]
        public string u_email { get; set; }

        [Display(Name = "Status")]
        [Required(ErrorMessage = "*")]
        public byte u_status { get; set; }

        [Display(Name = "Role")]
        [Required(ErrorMessage = "*")]
        public byte u_roleID { get; set; }
    
        public virtual role role { get; set; }
    }
}
